import {
  Badge,
  Container,
  Flex,
  HStack,
  Heading,
  Image,
  VStack,
} from "@chakra-ui/react";
import dynamic from "next/dynamic";
import Head from "next/head";

const MiniChart = dynamic(
  () => import("react-ts-tradingview-widgets").then((w) => w.MiniChart),
  {
    ssr: false,
  }
);

export default function Home() {
  return (
    <>
      <Head>
        <title>Petter Ivest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container width="100vw" maxWidth="full" height="full" bgColor="blue.900">
        <Flex flexDir="column" flex={1} gap="10px">
          <VStack>
            <Image
              alt="empresa logo"
              src="petrobras.png"
              boxSize="150px"
              objectFit="contain"
            />

            <Heading color="white" fontWeight="bold">
              PETR4
            </Heading>
            <HStack
              w="full"
              justifyContent="center"
              alignItems="center"
              flexWrap="wrap"
            >
              <Badge
                variant="solid"
                fontWeight="bold"
                padding={1}
                colorScheme="green"
              >
                IPO desde 2005
              </Badge>
              <Badge
                variant="solid"
                fontWeight="bold"
                padding={1}
                colorScheme="green"
              >
                IPO desde 2005
              </Badge>
              <Badge
                variant="solid"
                fontWeight="bold"
                padding={1}
                colorScheme="red"
              >
                Divida alta
              </Badge>
            </HStack>
          </VStack>

          <Flex justify="center" width="100%" height={250} mb="2">
            <iframe
              width="100%"
              src="https://www.youtube.com/embed/LWs7OL83S2c?start=1"
              title="YouTube video player"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowFullScreen
            ></iframe>
          </Flex>

          <MiniChart
            symbol="PETR4"
            locale="br"
            width="100%"
            height={400}
            colorTheme="dark"
          />
        </Flex>
      </Container>
    </>
  );
}
